version: '3'

services:
  db:
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sense_test
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - default
  app:
    build: .
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sense_test
      URL_VIA_CEP: https://viacep.com.br/ws/
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default

networks:
  default:
volumes:
  db_postgres: