"""criando tabela de localidades

Revision ID: 2119a3759645
Revises: 
Create Date: 2023-01-23 13:39:31.700847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2119a3759645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localidades',
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('localidade', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('data_consulta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cep')
    )
    op.create_index(op.f('ix_localidades_cep'), 'localidades', ['cep'], unique=False)
    op.create_index(op.f('ix_localidades_data_consulta'), 'localidades', ['data_consulta'], unique=False)
    op.create_index(op.f('ix_localidades_localidade'), 'localidades', ['localidade'], unique=False)
    op.create_index(op.f('ix_localidades_logradouro'), 'localidades', ['logradouro'], unique=False)
    op.create_index(op.f('ix_localidades_uf'), 'localidades', ['uf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_localidades_uf'), table_name='localidades')
    op.drop_index(op.f('ix_localidades_logradouro'), table_name='localidades')
    op.drop_index(op.f('ix_localidades_localidade'), table_name='localidades')
    op.drop_index(op.f('ix_localidades_data_consulta'), table_name='localidades')
    op.drop_index(op.f('ix_localidades_cep'), table_name='localidades')
    op.drop_table('localidades')
    # ### end Alembic commands ###
